AWS Batch new UI changes
aws-samples/aws-hpc-tutorials pull request #101
Opened 2020-11-28 02:23 UTC by amit-tyagi

I have made couple of changes to incorporate the new user interface for AWS Batch. The changes are for module V - Simulations with AWS Batch
1. Changed verbiage and images for e. Set Up Compute Environment.
2. Changed verbiage and images for f. Set Up a Job Queue.
3. Changed verbiage and images for g. Set Up a Job Definition.
4. Added the new cloud formation template as a new ECS Task execution role is required while setting up Job Definition.

2020-11-30 17:55 UTC, sean-smith commented
## Preview link: https://pr-101.db63t2jjt7llc.amplifyapp.com/05-aws-batch.html

2020-11-30 22:51 UTC, amit-tyagi commented on content/05-AWS Batch/05-setup-batch.md
> +7. For **Service role**, choose **AWSBatchServiceRole** so that AWS Batch can manage resources on your behalf.
I have made the necessary changes and commit them.

2020-12-10 21:10 UTC, perifaws requested changes

2020-12-10 21:10 UTC, perifaws commented on static/scripts/aws_batch/s3policy.yaml
> +#   aws cloudformation create-stack --stack-name 'S3InstanceRoleNvidiaDriversBucket' \
Why `NvidiaDriversBucket`?

2020-12-10 21:10 UTC, perifaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +Next, take a closer look at **compute environment**, **job queue**, and **job definition** you created.
Title case for the CE, JQ and JD

2020-12-10 21:10 UTC, perifaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +14. For **Name**, type **EXPORT_S3_BUCKET_URL**. For **Value**, choose the bucket you previously created. To find the name of the S3 bucket, run the following command in your terminal or view the S3
Add that they need to use `s3://bucket-name`, there were confusions around the missing `s3://`.

2020-12-10 21:10 UTC, perifaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +11. Do not select any values for **Volumes**, **Mount points**, and **Ulimits**.
merge with 12 here

2020-12-10 21:10 UTC, perifaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +1. In the **AWS Batch Dashboard**, choose **Job definitions** from the left pane, then **Create**. Ignore the *Loading resources* message in the grid as this is a known bug.
remove known bug

2020-12-10 21:10 UTC, perifaws commented on content/05-AWS Batch/06-setup-batch-job-queue.md
> +2. Under **Job queue configuration** section, type a **Job queue name**.
Job Queue instead of Job queue

2020-12-10 21:10 UTC, perifaws commented on content/05-AWS Batch/06-setup-batch-job-queue.md
> +6. Under **Connected compute environments**, select a compute environment that you created previously.
Compute Environment, use title case here

2020-12-14 16:42 UTC, mhuguesaws commented
Will have to create a new PR in order to keep the process moving along, since the author has left.

2020-12-14 16:53 UTC, mhuguesaws commented on content/05-AWS Batch/06-setup-batch-job-queue.md
> +6. Under **Connected compute environments**, select a compute environment that you created previously.
Addressed in the new PR

2020-12-14 16:53 UTC, mhuguesaws commented on content/05-AWS Batch/06-setup-batch-job-queue.md
> +2. Under **Job queue configuration** section, type a **Job queue name**.
Addressed in the new PR

2020-12-14 16:53 UTC, mhuguesaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +1. In the **AWS Batch Dashboard**, choose **Job definitions** from the left pane, then **Create**. Ignore the *Loading resources* message in the grid as this is a known bug.
Addressed in the new PR

2020-12-14 17:00 UTC, mhuguesaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +11. Do not select any values for **Volumes**, **Mount points**, and **Ulimits**.
Addressed in the new PR

2020-12-14 17:04 UTC, mhuguesaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +14. For **Name**, type **EXPORT_S3_BUCKET_URL**. For **Value**, choose the bucket you previously created. To find the name of the S3 bucket, run the following command in your terminal or view the S3
Addressed in the new PR

2020-12-14 17:04 UTC, mhuguesaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +Next, take a closer look at **compute environment**, **job queue**, and **job definition** you created.
Not addressed, I guess this is to match the spelling in the console

2020-12-14 17:08 UTC, closed without merging