Fixed Carla simulation and DCV licensing
aws-samples/aws-hpc-tutorials pull request #13
Opened 2020-08-03 11:41 UTC by qyjohn

*Issue #, if available:*

1. The NVIDIA driver was not properly installed on g2.2xlarge, causing the Carla simulation to fail.
2. The EC2 instance for NICE DCV needs an IAM role to access licensing buckets on S3.

*Description of changes:*

1. Created additional scripts in carla_0.9.5_ami_generation_g2.zip to address the NVIDIA driver installation problem. Changed the commands in the tutorial to reflect this change.
2. Created a CloudFormation template and a bash script to create the instance profile needed to access the NICE DCV licensing buckets on S3. Created the additional content pages to describe the additional steps.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-08-03 18:05 UTC, sean-smith commented
As a general comment, can you separate this into two commits:
1. Carlo AWS Batch
2. Nice DCV

To do so simply reset the last two commits then re-commit like so:

```bash
git reset HEAD~2
git add content/05-AWS Batch
git commit -sm "Fix Carla Simulation"
git commit -sam "Add License to NICE DCV"
git push --force [remote] [branch]
```

2020-08-03 18:09 UTC, sean-smith commented on content/06-nice-dcv/standalone/11-dcv-licensing.md
> +bash dcv_dcv_role.sh
Let's include this script in the website source under `static/scripts/dcv_license.zip` then you can curl it from `https://www.hpcworkshops.com/scripts/dcv_license.zip`

2020-08-03 18:13 UTC, sean-smith commented on content/06-nice-dcv/standalone/11-dcv-licensing.md
> +bash dcv_dcv_role.sh
What does this script do?

2020-08-03 18:13 UTC, sean-smith commented on content/06-nice-dcv/standalone/11-dcv-licensing.md
> +When you connect to NICE DCV using the NICE DCV client, you might notice the following notification regarding NICE DCV licensing.
Is there any way we can set this up before they launch the instance so as to avoid the license error altogether?

2020-08-03 22:13 UTC, kraman-aws commented on content/06-nice-dcv/standalone/11-dcv-licensing.md
> +When you connect to NICE DCV using the NICE DCV client, you might notice the following notification regarding NICE DCV licensing.
Yes agree, would be best if we can add this in Section VI A. i.e. creating a role with the policy (for license access) in the console and attaching that role

2020-08-03 22:46 UTC, qyjohn commented on content/06-nice-dcv/standalone/11-dcv-licensing.md
> +When you connect to NICE DCV using the NICE DCV client, you might notice the following notification regarding NICE DCV licensing.
Agree. I will move this part to VI.a, creating the role after "Generate an SSH Key-pair" but before "Create an Amazon EC2 Instance with NICE DCV AMI ". This way we can attach that role when creating the EC2 instance. Also, I will delete the role in VI.d after the EC2 instance is deleted.

2020-08-03 22:48 UTC, qyjohn commented on content/06-nice-dcv/standalone/11-dcv-licensing.md
> +bash dcv_dcv_role.sh
This script uses CloudFormation to create an instance profile that allows access to the NICE DCV licensing buckets.

2020-08-03 23:44 UTC, qyjohn commented
Done with the following:

1. Separating the changes into two commits, one to address the issue with Carla simulation, the other to address the issue with NICE DCV licensing.
2. With NICE DCV, create the instance profile before creating the EC2 instance. Also add the instructions to delete the instance profile after deleting the EC2 instance.

2020-08-04 00:22 UTC, sean-smith commented on content/06-nice-dcv/standalone/08-deploy-ec2.md
> +While waiting for the instance profile to be created, you can review the content in **cfn_dcv_role.sh** and **cfn_dcv_policy.yaml** to understand what the the behavior of the CloudFormation template.
Add a note as to why this is needed and link to the DCV docs on this.

2020-08-04 00:24 UTC, sean-smith commented on content/06-nice-dcv/standalone/11-terminate-ec2-dcv.md
> +aws cloudformation delete-stack --stack-name DCVWorkshop
Change stack name e.g. something like: `DCVInstanceProfile`

2020-08-04 00:25 UTC, sean-smith commented on content/05-AWS Batch/01-requirement.md
> +curl https://s3.amazonaws.com/av-workshop/carla_0.9.5_ami_generation_g2.zip \
update bucket

2020-08-04 00:35 UTC, sean-smith commented on content/06-nice-dcv/standalone/08-deploy-ec2.md
> +curl https://www.hpcworkshops.com/scripts/dcv_license.zip -o dcv_license.zip
Please add the non-zipped directory to Github as well

2020-08-04 01:09 UTC, qyjohn commented on content/06-nice-dcv/standalone/08-deploy-ec2.md
> +While waiting for the instance profile to be created, you can review the content in **cfn_dcv_role.sh** and **cfn_dcv_policy.yaml** to understand what the the behavior of the CloudFormation template.
done.

2020-08-04 01:09 UTC, qyjohn commented on content/06-nice-dcv/standalone/11-terminate-ec2-dcv.md
> +aws cloudformation delete-stack --stack-name DCVWorkshop
done

2020-08-04 01:09 UTC, qyjohn commented on content/05-AWS Batch/01-requirement.md
> +curl https://s3.amazonaws.com/av-workshop/carla_0.9.5_ami_generation_g2.zip \
done.

2020-08-04 01:09 UTC, qyjohn commented on content/06-nice-dcv/standalone/08-deploy-ec2.md
> +curl https://www.hpcworkshops.com/scripts/dcv_license.zip -o dcv_license.zip
done.

2020-09-04 22:32 UTC, kraman-aws approved these changes
Tested the DCV related changes, works well

2020-09-04 22:33 UTC, kraman-aws approved these changes
Tested DCV changes, works well

2020-09-14 23:20 UTC, sean-smith commented
**Action Items**
1. Update to g3 instances which have better availability than g2
2. Remove extra files such as build_g2.sh and image_g2.json
3. Check to see if running on Cloud9
4. Drop mac support

2020-09-22 02:43 UTC, perifaws commented
@qyjohn a few more fixes and we should be good to go.

2020-09-23 23:06 UTC, sean-smith commented on content/05-AWS Batch/00-environment.md
> +6. Launch an EC2 instance with an **Amazon Linux 2** AMI. In ***Step 3: Configure Instance Details*, locate **IAM role** and select the newly created **hpcworkshop-admin** from the drop-down selectio
Convert this to Cloud9. Disable the default AWS credentials on Cloud9.

2020-09-23 23:06 UTC, sean-smith commented on content/05-AWS Batch/00-environment.md
> +6. Launch an EC2 instance with an **Amazon Linux 2** AMI. In ***Step 3: Configure Instance Details*, locate **IAM role** and select the newly created **hpcworkshop-admin** from the drop-down selectio
Missing `**` after `Step 3: Configure Instance Details`

2020-09-23 23:06 UTC, sean-smith commented on content/05-AWS Batch/02-build-ami-packer.md
> +bash build_g2.sh $INSTANCE_ROLE
build_g2.sh -> build.sh

2020-09-23 23:06 UTC, sean-smith commented on content/05-AWS Batch/02-build-ami-packer.md
> +The building process is handled by [Packer](https://www.packer.io/) from HashiCorp. The process involves multiple reboots to update to the latest driver and kernel modules. We recommend that you to c
same here

2020-09-23 23:06 UTC, sean-smith commented on content/05-AWS Batch/_index.md
> -{{% notice info %}}
restore this

2020-09-23 23:46 UTC, perifaws requested changes
Some changes to make things more uniform

2020-09-23 23:46 UTC, perifaws commented on content/05-AWS Batch/00-environment.md
> +6. Launch an EC2 instance with an **Amazon Linux 2** AMI. In ***Step 3: Configure Instance Details*, locate **IAM role** and select the newly created **hpcworkshop-admin** from the drop-down selectio
* instead of ***

2020-09-23 23:46 UTC, perifaws commented on content/05-AWS Batch/05-setup-batch.md
> -![AWS Batch](/images/aws-batch/batch5.png)
if replacing one can remove the g3 at the end and replace batch5 directly

2020-09-24 00:19 UTC, qyjohn commented on content/05-AWS Batch/00-environment.md
> +6. Launch an EC2 instance with an **Amazon Linux 2** AMI. In ***Step 3: Configure Instance Details*, locate **IAM role** and select the newly created **hpcworkshop-admin** from the drop-down selectio
Done.

2020-09-24 00:20 UTC, qyjohn commented on content/05-AWS Batch/00-environment.md
> +6. Launch an EC2 instance with an **Amazon Linux 2** AMI. In ***Step 3: Configure Instance Details*, locate **IAM role** and select the newly created **hpcworkshop-admin** from the drop-down selectio
Changed to Cloud9 and removed this.

2020-09-24 00:20 UTC, qyjohn commented on content/05-AWS Batch/02-build-ami-packer.md
> +bash build_g2.sh $INSTANCE_ROLE
Done.

2020-09-24 00:20 UTC, qyjohn commented on content/05-AWS Batch/02-build-ami-packer.md
> +The building process is handled by [Packer](https://www.packer.io/) from HashiCorp. The process involves multiple reboots to update to the latest driver and kernel modules. We recommend that you to c
Done.

2020-09-24 00:20 UTC, qyjohn commented on content/05-AWS Batch/_index.md
> -{{% notice info %}}
Done.

2020-09-24 00:20 UTC, qyjohn commented on content/05-AWS Batch/00-environment.md
> +6. Launch an EC2 instance with an **Amazon Linux 2** AMI. In ***Step 3: Configure Instance Details*, locate **IAM role** and select the newly created **hpcworkshop-admin** from the drop-down selectio
Changed to Cloud9 and this was removed.

2020-09-24 00:20 UTC, qyjohn commented on content/05-AWS Batch/05-setup-batch.md
> -![AWS Batch](/images/aws-batch/batch5.png)
Done.

2020-09-24 00:47 UTC, sean-smith approved these changes

2020-09-24 01:30 UTC, perifaws approved these changes

2020-09-24 01:31 UTC, perifaws approved these changes
Approved

2020-09-24 01:31 UTC, merged