Commiting AWS Batch Lab
aws-samples/aws-hpc-tutorials pull request #132
Opened 2021-10-12 22:41 UTC by tccaws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-12 22:45 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
> +![AWS Batch](/images/aws-batch/compute-env-5.png)
Change allocation strategy by BEST_FIT_PROGRESSIVE on the image

2021-10-12 22:49 UTC, mhuguesaws commented on content/05-AWS Batch/10-run-array-job.md
> +FROM amazonlinux:latest
```suggestion
FROM public.ecr.aws/amazonlinux/amazonlinux:latest
```

2021-10-12 23:00 UTC, mhuguesaws commented on content/05-AWS Batch/11-job-dependency.md
> +- A **Master** job will define the work to be carried out and write this configuration to a specified S3 bucket. This is effectively accomplished by executing the previous mktests.sh script and uploa
```suggestion
- A **Leader** job will define the work to be carried out and write this configuration to a specified S3 bucket. This is effectively accomplished by executing the previous mktests.sh script and uploading the resulting stress-tests.txt file to the specified S3 bucket.
```

2021-10-12 23:00 UTC, mhuguesaws commented on content/05-AWS Batch/11-job-dependency.md
> +You will implement a job dependency such that the Master job runs first and the Worker array job will only start on successful completion of the Master job.
```suggestion
You will implement a job dependency such that the Leader job runs first and the Worker array job will only start on successful completion of the Master job.
```

2021-10-14 23:13 UTC, tccaws commented on content/05-AWS Batch/05-setup-batch.md
> +![AWS Batch](/images/aws-batch/compute-env-5.png)
I updated this image and pushed the change.

2021-10-14 23:13 UTC, tccaws commented
Waiting for review and merge.

2021-11-01 19:43 UTC, mhuguesaws commented on content/05-AWS Batch/00-environment.md
> +- Expand the root volume to at least 20GB in capacity to allow container images to be built.
```suggestion
- Expand the root volume to at least 20GiB in capacity to allow container images to be built.
```

2021-11-01 20:36 UTC, mhuguesaws reviewed
Please address comments

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/00-environment.md
> +4. Select the root volume for your Cloud9 instance and resize it to be at least 20GB in size by choosing **Actions / Modify volume /**. ![Modify the root volume](/images/aws-batch/root-volume-3.png)
```suggestion
4. For actions, choose **Modify Volume** and for **Size** enter 20GiB. ![Modify the root volume](/images/aws-batch/root-volume-3.png)
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/00-environment.md
> +5. Return to your [ Cloud9 EC2 instance](https://console.aws.amazon.com/ec2/v2/home?#Instances:search=cloud9;sort=desc:launchTime) and start it up by selecting the instance and choosing **Instance st
```suggestion
5. Open Amazon EC2 Console [link](https://console.aws.amazon.com/ec2/v2/home?#Instances:search=cloud9;sort=desc:launchTime) to find your Cloud9 instance.
6. Select the Cloud9 instance
7. For **Instance state**, select **Reboot instance**
8. Open AWS Cloud9 Console [link](https://console.aws.amazon.com/cloud9) and select **Open IDE**
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/01-roles.md
> +1. Open the IAM console [deep link](<https://console.aws.amazon.com/iam/home#/roles%24new?step=type&commonUseCase=EC2%2BEC2&selectedUseCase=EC2&policies=arn:aws:iam::aws:policy%2FAdministratorAccess>
```suggestion
1. Open the IAM console [link](<https://console.aws.amazon.com/iam/home#/roles%24new?step=type&commonUseCase=EC2%2BEC2&selectedUseCase=EC2&policies=arn:aws:iam::aws:policy%2FAdministratorAccess>) to create an IAM Role.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/01-roles.md
> +1. Open the Amazon EC2 [deep link](<https://console.aws.amazon.com/ec2/v2/home#Instances:tag:Name=aws-cloud9-myCloud9Env>) to find your Cloud9 instance.
```suggestion
1. Open the Amazon EC2 [link](<https://console.aws.amazon.com/ec2/v2/home#Instances:tag:Name=aws-cloud9-myCloud9Env>) to find your Cloud9 instance.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/02-build-docker-container.md
> +In this step, you will create a simple "Dockerfile" with the specifications for a container and then use Docker commands to build and test a container image on your Cloud9 instance.
```suggestion
In this step, you will create a **Dockerfile** file that contains the steps to build and test a container image on your Cloud9 instance. 
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/02-build-docker-container.md
> +1. Open a new file in the Cloud9 editor named "Dockerfile" and cut and paste the following contents:
```suggestion
1. In the Cloud9, create a new file in the Cloud9 editor named **Dockerfile** and execute the following command:
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/02-build-docker-container.md
> +FROM public.ecr.aws/amazonlinux/amazonlinux:latest
```suggestion
cat > Dockerfile << EOF
FROM public.ecr.aws/amazonlinux/amazonlinux:latest
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/02-build-docker-container.md
> +RUN cat /docker-entrypoint.sh
```suggestion
RUN cat /docker-entrypoint.sh
EOF
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/02-build-docker-container.md
> +1. Build a container with the tag "stress-ng" from your Dockerfile by excuting the following command:
```suggestion
2. Build a container with the tag "stress-ng" from your Dockerfile by executing the following command in the Cloud9 terminal:
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
> +In this step, you will set up an AWS Batch "Compute Environment" using the AWS Management Console.
```suggestion
In this step, you will set up an AWS Batch **Compute Environment** using the AWS Management Console.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
> +Compute environments can be thought of as computational clusters consisting of one or more EC2 instance types, or simply as the number of cores you want to use to run your jobs. For more information
```suggestion
Compute environments are [Amazon ECS](https://aws.amazon.com/ecs/) clusters consisting of one or more EC2 instance types, or simply as the number of vCPUs you want to use to run your jobs. For more information on the compute environments, see [Compute Environments](https://docs.aws.amazon.com/batch/latest/userguide/compute_environments.html).
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
> +6. Click **Additional settings** and for **Service role**, choose **Batch service-linked role**. The role allows the AWS Batch service to make calls to the required AWS API operations on your behalf.
```suggestion
5. Click **Additional settings** and for **Service role**, choose **Batch service-linked role**. The role allows the AWS Batch service to make calls to the required AWS API operations on your behalf. For more information, see [**Using Service-Linked Roles**](https://docs.aws.amazon.com/batch/latest/userguide/using-service-linked-roles.html). For **Instance role** choose **ecsInstanceRole**.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
> +7. Under **Instance configuration**, choose **On-demand** for **Provisioning model**. This option allows EC2 to create resources for you as required.
```suggestion
6. Under **Instance configuration**, choose **On-demand** for **Provisioning model**. This option allows EC2 to create resources for you as required.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
>  19. Once the environment is ready, it will be visible under **Compute environments** section. Make sure *Status* is **VALID** and *State* is **ENABLED**.
```suggestion
20. Once the environment is ready, it will be visible under **Compute environments** section. Make sure *Status* is **VALID** and *State* is **ENABLED**.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/05-setup-batch.md
> +At this point, you have done the hard part! Continue to the next step toset up a job queue.
```suggestion
At this point, you have created a **Compute Environment** that will be used by the **Job Queue** that you will setup in the next step.
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/06-setup-batch-job-queue.md
> +In this step, you will set up a job queue. You submit your jobs to a queue and they are dispatched to the compute environment(s) of your choosing in order of priority. If you want to learn more about
```suggestion
In this step, you will set up a **Job Queue (JQ)**. You submit your jobs to a queue and they are dispatched to the compute environment(s) of your choosing in order of priority. If you want to learn more about job queues, see [Job Queues](https://docs.aws.amazon.com/batch/latest/userguide/job_queues.html).
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/07-setup-batch-job-definition.md
> +In this step, you will set up a template for your jobs, known as a job definition. A job definition is not required, but is good practice so that you can keep track of how your jobs are launched. For
```suggestion
In this step, you will set up a template for your jobs, known as a **Job Definition (JD)**. For more information about **Job Definitions**, see [Job Definitions](https://docs.aws.amazon.com/batch/latest/userguide/job_definitions.html).
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +1. Choose **Compute environments** section. Select the compute environment you created for this workshop and choose **Delete**. Note that job queues must be deleted or disassociated from compute envi
```suggestion
5. Choose **Compute environments** section. Select the compute environment you created for this workshop and choose **Delete**. Note that job queues must be deleted or disassociated from compute environments before the compute environment can be deleted. (**Or, use the following script to delete all existing Compute Environments**.)
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +cd ~
```suggestion

```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +cd ~
```suggestion
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +cd ~
```suggestion
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +bash remove-jq.sh
```suggestion
bash ~/remove-jq.sh
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +bash remove-ce.sh
```suggestion
bash ~/remove-ce.sh
```

2021-11-01 20:36 UTC, mhuguesaws commented on content/05-AWS Batch/12-optional.md
> +bash remove-repos.sh
```suggestion
bash ~/remove-repos.sh
```

2021-11-16 14:14 UTC, mhuguesaws commented on content/05-AWS Batch/00-environment.md
> +<<<<<<< HEAD
Please review those changes

2021-11-16 14:14 UTC, mhuguesaws commented on content/05-AWS Batch/00-environment.md
> +<<<<<<< HEAD
Please review the changes

2021-11-16 14:16 UTC, mhuguesaws requested changes
Please address the merge conflicts that have been committed

2021-11-17 22:16 UTC, mhuguesaws submitted a review, later dismissed
LGTM

2021-11-17 22:58 UTC, mhuguesaws approved these changes
LGTM

2021-11-17 22:58 UTC, merged