Add Distributed ML section
aws-samples/aws-hpc-tutorials pull request #16
Opened 2020-09-09 15:17 UTC by nonatofabio

Signed-off-by: Fabio Nonato <fnp@amazon.com>

*Issue #, if available:*

*Description of changes:*
Section VIII added with distributed ML application.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-15 23:53 UTC, mhuguesaws commented
Waiting on #21 before starting review.

2020-09-16 14:51 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +
One line spacing between to stay consistent

2020-09-16 15:52 UTC, mhuguesaws requested changes
Please look at the different comments that should be addressed

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +# Start configuration of NCCL and EFA only if CUDA and EFA present
No caps on first letter

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +    ./autogen.sh
Use environment variable already defined on the configure line

```
OPENMPI_DIRECTORY=/opt/amazon/openmpi
./configure --with-mpi=\$OPENMPI_DIRECTORY --with-libfabric=\$EFA_DIRECTORY --with-nccl=\$NCCL_DIRECTORY/build --with-cuda=\$CUDA_DIRECTORY
```

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +    export PATH=/opt/amazon/openmpi/bin:\$PATH
Replace by

```
export PATH=\$OPENMPI_DIRECTORY/bin:\$PATH
```

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +    pip install -e /shared/fairseq -U
Replace to use env variable

```
pip install -e \$FAIRSEQ_DIRECTORY -U
```

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +# Configuring the conda environment
no caps on first letter

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +# generate a uniqe postfix
fix spelling of `unique` instead of `uniqe`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +echo "Your bucket name will be mlbucket-${BUCKET_POSTFIX}"
Suggest to export the bucket name as an environment variable. That make easier the bucket name change easier in the future and avoid typos

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +    cd /home/ec2-user/aws-ofi-nccl
Replace by cd \$AWS_OFI_DIRECTORY

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +Before continuing to the next step, check the content of your bucket using the AWS CLI with the command `aws s3 ls s3://mlbucket-${BUCKET_POSTFIX}` or the [AWS console](https://s3.console.aws.amazon.
remove "to the next step"

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +Next, create a cluster configuration file for the ML cluster.
remove ` Now, build our AWS ParallelCluster configuration.` it is repetitive with the following sentence `Next, create a cluster configuration file for the ML cluster.`

Suggested replacement
`In the following step, you will define the configuration of the ML cluster by creating the AWS ParallelCluster configuration file.`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +In this step, you create an cluster configuration that supports your Distributed MAchine Learning task.
**a** cluster

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +In this step, you create an cluster configuration that supports your Distributed MAchine Learning task.
Distributed M**a**chine Learning

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +In particular you need to be able to [examine the FSx file system](../04-amazon-fsx-for-lustre/03-check-fs.html) and [examine the EFA enabled instance](../07-efa/02-check-efa.html).
In particular,

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +the cluster creation continues even if the termional session you are on gets terminated. To check on the status of the creation, use the command: `pcluster status my-ml-cluster -c my-ml-cluster.ini`.
Capital on first letter `The`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/02-data-preprocessing.md
> +In this section you will run a data preprocessing step using the `fairseq` command line tool and `srun`. Fairseq provides the `fairseq-preprocess` that creates a vocabulary and binarizes the training
In this section, you run

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/02-data-preprocessing.md
> +In this section you will run a data preprocessing step using the `fairseq` command line tool and `srun`. Fairseq provides the `fairseq-preprocess` that creates a vocabulary and binarizes the training
Remove link anchor

Current
```
https://fairseq.readthedocs.io/en/latest/command_line_tools.html#
```

After
```
https://fairseq.readthedocs.io/en/latest/command_line_tools.html
```

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +# create the cluster configuration
In the previous code blocks, they started with `#!/bin/bash` but not here. Stay consistent across the lab. 
The other labs do not start code block with `#!/bin/bash`.

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/02-data-preprocessing.md
> +Before running the preprocessing, check if **Slurm** is available and the queue is empty by running `sinfo -ls` and `squeue -ls`. At this stage you should have _ZERO_ compute nodes and an empty queue
Make SLURM all capitals to stay consistent with previous content

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/02-data-preprocessing.md
> +The preprocess data is available to all compute node in the _/lustre_ directory. Run the following command to examine the data: `ll -alh /lustre/data/wikitext-103`
Suggest to replace `ll -alh /lustre/data/wikitext-103` by `ls -alh /lustre/data/wikitext-103`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +export LD_LIBRARY_PATH=$HOME/nccl/build/lib:/usr/local/cuda/lib64:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:$LD_LIBRARY_PATH
```
export LD_LIBRARY_PATH=\$HOME/nccl/build/lib:/usr/local/cuda/lib64:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:\$LD_LIBRARY_PATH```

Potentially you can export the NCCL build, CUDA and OpenMPI directory environment variable define in a previous step to be reused here

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +python -m torch.distributed.launch --nproc_per_node=\$PROC_PER_NODE --nnodes=\$WORLD_SIZE_JOB --node_rank=\$RANK_NODE --master_addr=\${MASTER_ADDR_JOB} --master_port=\${MASTER_PORT_JOB} \
Suggest to have one argument per line

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +    --bucket-cap-mb \$BUCKET_CAP_MB \
Indentation

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +The script starts by setting up paths for the training data, output and checkpointing. All paths reference _/lustre_ and are visible by all compute nodes. Next, the script sets environment variables
Fix grammar -> `It also sets`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +The above commands adds a **Slurm** job to the queue and logs its output to the _out\_<job_id>.out_ file. Check the status of the job with `squeue -ls` and `sinfo -ls`. If there are less than the req
Fix grammar `add`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +The above commands adds a **Slurm** job to the queue and logs its output to the _out\_<job_id>.out_ file. Check the status of the job with `squeue -ls` and `sinfo -ls`. If there are less than the req
Avoid guaranteeing time

Before
` This process can take up to 7 minutes.`

After
` This process takes few minutes.`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +To check the progress of the job once it starts, `tail` the output file with the following command: `tail -f out_<job_id>.out`.
Suggest

`Once the job is started, you can check the progress by...`

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +If you wish to persist the model checkpoints for later use, copy them to the S3 bucket with the following command - make sure to replace `<your-bucket-postfix>` with your bucket's id:
Don't understand this sentence maybe I am not enough familiar with ML ?

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +aws s3 cp checkpoints s3://mlbucket-<your-bucket-postfix>/checkpoints --recursive
Why not using the `$BUCKET_POSTFIX` variable ?

2020-09-16 15:52 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/04-delete-ml-cluster.md
> +Note: Files stored in the Amazon S3 bucket and on AWS Cloud9 will incur small charges (less than a dollar a month if the tutorial was followed as written.) The Cloud9 IDE will stop (not terminate) 30
Avoid quantification.
`will incur **charges**`

2020-09-21 18:35 UTC, nonatofabio commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +echo "Your bucket name will be mlbucket-${BUCKET_POSTFIX}"
@mhuguesaws , agree, however trying to keep the same pattern as prior sections.

2020-09-21 18:38 UTC, nonatofabio commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +Next, create a cluster configuration file for the ML cluster.
Minor change to the suggestion:
`Next, define the configuration of the ML cluster by creating the AWS ParallelCluster configuration file.`

2020-09-21 18:43 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +echo "Your bucket name will be mlbucket-${BUCKET_POSTFIX}"
Agreed, Let's revisit that later

2020-09-21 18:43 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/00-upload-training-data.md
> +Next, create a cluster configuration file for the ML cluster.
LGTM

2020-09-22 20:45 UTC, nonatofabio commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +# create the cluster configuration
Will unify and have it as the rest of the workshop, without `#!/bin/bash`

2020-09-22 20:53 UTC, nonatofabio commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +export LD_LIBRARY_PATH=$HOME/nccl/build/lib:/usr/local/cuda/lib64:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:$LD_LIBRARY_PATH
Those exports commands get executed in the post installation script, not in the same environment as the SLURM job executor. To avoid the missing path I rather call these out explicitly. Other solution would be to modify the `.bashrc` for the SLURM execution user. Don't think this extra step is worth the trouble. Open for suggestions!

2020-09-22 21:11 UTC, nonatofabio commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +aws s3 cp checkpoints s3://mlbucket-<your-bucket-postfix>/checkpoints --recursive
This variable is only set on the `pcluster` admin machine. The context here is the head-node of the cluster, to the env variable is not there.

2020-09-22 21:38 UTC, mhuguesaws commented on content/08-ml-on-parallelcluster/03-distributed-data-parallel.md
> +aws s3 cp checkpoints s3://mlbucket-<your-bucket-postfix>/checkpoints --recursive
Noted

2020-09-22 22:07 UTC, nonatofabio commented on content/08-ml-on-parallelcluster/01-create-ml-cluster.md
> +- Set the compute cluster type to be `cluster_type=spot`. [AWS EC2 Spot instances](https://aws.amazon.com/ec2/spot) are available for less than the cost of On-Demand Instances, but it is possible tha
Modified the callout for Spot instance type as requested by the service team.

2020-09-22 22:18 UTC, mhuguesaws approved these changes
LGTM

2020-09-22 23:01 UTC, merged