Updates and changes from feedback.
aws-samples/aws-hpc-tutorials pull request #336
Opened 2022-10-27 18:13 UTC by t-brown

- Updated the agenda to reflect current changes.
- Included changes from feedback by testers.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-01 04:58 UTC, kraman-aws commented on content/02-aws-getting-started/06-start-aws-cli.md
> +wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O $HOME/.local/bin/yq && chmod +x $HOME/.local/bin/yq
thanks for adding this. i assume you confirmed it picks the right version and does not need to be added in PATH?

2022-11-01 05:01 UTC, kraman-aws commented on content/03-hpc-aws-parallelcluster-workshop/09-connect-cluster.md
> +In addition to DCV, you can connect to your cluster via SSH using SSM.
above says you connect via SSM, here it says DCV.

2022-11-01 05:02 UTC, kraman-aws commented on content/03-hpc-aws-parallelcluster-workshop/09-connect-cluster.md
> +3. Next to launch a terminal (where the rest of the lab will run) we'll click **Activities** > **Terminal**:
is this via DCV or via SSM?

2022-11-01 05:04 UTC, kraman-aws commented on content/03-hpc-aws-parallelcluster-workshop/14-exit-cluster.md
> +We need to stop the compute cluster, so we can update it in the next lab. In your AWS Cloud9 terminal window paste the following command
We need to stop the compute fleet, so ..

2022-11-01 05:08 UTC, kraman-aws requested changes
added a few comments, rest looks good to me. can you make sure that this PR gets merged  https://github.com/aws-samples/aws-hpc-tutorials/pull/332 first before merging this

2022-11-01 16:12 UTC, t-brown commented on content/02-aws-getting-started/06-start-aws-cli.md
> +wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O $HOME/.local/bin/yq && chmod +x $HOME/.local/bin/yq
Yes, `~/.local/bin` is already in the users path.

2022-11-03 00:41 UTC, mhuguesaws reviewed
Please address conflicts.

2022-11-08 06:04 UTC, kraman-aws approved these changes

2022-11-08 19:02 UTC, merged