Sc20 staging update severless
aws-samples/aws-hpc-tutorials pull request #53
Opened 2020-10-30 10:38 UTC by perifaws

Update of the serverless lab for more clarity. Addition updates will be made

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-31 06:14 UTC, kraman-aws commented on content/04-serverless/02-serverless-iam/_index.md
> +IAM controls who or what can conduct actions on resources. For example, an instance can be allowed to access the APIs to create new instances. In the present case, we will enable the nodes of your cl
Better to spell it out for first mention  "Identity and Access Management (IAM) controls ..."

2020-10-31 06:16 UTC, kraman-aws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now we will create our policy. We will download it for didactic purposes but it is not required.
didactic? typo

2020-10-31 06:23 UTC, kraman-aws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +You don't actually need to download the Cloudformation template to your Cloud9 instance. Indeed, it is possible to run Cloudformation templates that are already stored on S3. For that matter you coul
For that matter you could replace the `--template**-body** file://serverless-template.yaml`

2020-10-31 06:28 UTC, kraman-aws commented on content/04-serverless/03-configure-pc-serverless.md
> -2. Modify the AWS ParallelCluster config file created earlier. Note the modified items are highlighted:
is it ok to just reference to the config file created earlier. should we also specify the name and path where this was created? (i.e. my-cluster-config.ini in ~/environment)

2020-10-31 06:29 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +Serverless functions, such as AWS Lambda, allow you to run code without provisioning or managing servers. It can be particularly useful to automate tasks or an infrastructure. In the present case we
This avoids the need for our cluster ..

2020-10-31 06:36 UTC, kraman-aws commented on content/04-serverless/06-slurm-lambda-config/06-config1.md
> +3. In the **Key** text box, enter the text `MY_S3_BUCKET`, in the **Value** field add the name of the S3 bucket that as created during [the very first step](/04-serverless/02-iam-policy-serverless.ht
not sure if this the Amplify preview but the link to the "very first step" seems to take to the SC20 Tutorial Resources page. we should review again once merged

2020-10-31 06:37 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/_index.md
> +Remember the bucket you crated in [**section b**](/04-serverless/02-iam-policy-serverless.html)? We will need its name for the following steps.
not sure if this the Amplify preview but the link to the "section b" seems to take to the SC20 Tutorial Resources page. we should review again once merged

2020-10-31 06:39 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/07-final1.md
> +2. Then click on **Create policy**. This will open a new tab in your Browser.
In the preview, the bullet numbering seems to be broken. Everything is shown as 1.

2020-10-31 06:42 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/07-final2.md
> +title = "- Configure the function timeout"
Title requires change. It says "Configure the function timeout", should be something  like "Create or Add a new policy"

2020-10-31 06:43 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/07-final2.md
> +3. Paste the policy below in the JSON editor and do not forget to replace **\<REGION\>** and **\<YOUR-S3-BUCKET-NAME\>** with the values you retrieved earlier. This policy enables you Lambda function
This policy enables you**r** Lambda function

2020-10-31 06:53 UTC, kraman-aws commented on content/04-serverless/09-interact-api/08-gateway1.md
> +2. Choose an API type, scroll down to **REST API** and click on Build. Do not choose the non-private **REST API** as you are building a public facing API here. Once on the next page click on **OK** t
Hmm "Do or Do not"?  Since we are building a public facing API, should be Choose the non-private REST API

2020-10-31 06:53 UTC, kraman-aws commented on content/04-serverless/09-interact-api/08-gateway1.md
> +3. You will now create a new API, select the radio box **New API**. Enter the **API name** (e.g. `SlurmFrontEndAPI`). Ensure that the **Endpoint Type** is **Regional**. When you are done, click on **
The bullet numbering seems to be messed up again

2020-10-31 06:58 UTC, kraman-aws commented on content/04-serverless/09-interact-api/08-gateway2.md
> +    ```
Hmm, this is showing the the create policy steps again.

2020-10-31 06:58 UTC, kraman-aws commented on content/04-serverless/09-interact-api/08-rename3.md
> +11. Now your API is deployed! Please take note of the API's **Invoke URL**. You will be using this URL to interact with your API.
Bullet should be 3.

2020-10-31 06:59 UTC, kraman-aws commented on content/04-serverless/09-interact-api/08-rename3.md
> +11. Now your API is deployed! Please take note of the API's **Invoke URL**. You will be using this URL to interact with your API.
Bullet should be 3.

2020-10-31 07:03 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-gateway3.md
> +1. Run the following command to submit, compile and run HPCCG.
HPCG (typo)

2020-10-31 07:07 UTC, kraman-aws requested changes
I have added my comments. Overall looks great. Not sure if this is Amplify again but the "next (>)" , "previous(<)" arrows seems to be not working correctly. It jumps to a complete different section

2020-10-31 14:39 UTC, Perif commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now we will create our policy. We will download it for didactic purposes but it is not required.
Will fix, the meaning appears to be a bit different between French and English.

2020-10-31 18:36 UTC, perifaws commented on content/04-serverless/07-slurm-lambda-final/07-final1.md
> +2. Then click on **Create policy**. This will open a new tab in your Browser.
This may be due to Amplify, I have fixed the formatting

2020-10-31 18:39 UTC, perifaws commented on content/04-serverless/09-interact-api/08-gateway1.md
> +3. You will now create a new API, select the radio box **New API**. Enter the **API name** (e.g. `SlurmFrontEndAPI`). Ensure that the **Endpoint Type** is **Regional**. When you are done, click on **
Amplify, seems to happen when we add an image between items in a numbered list.

2020-10-31 19:01 UTC, perifaws commented
@kraman-aws update pushed.

2020-11-01 23:26 UTC, perifaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now we will create our policy. We will download it for didactic purposes but it is not required.
It has been updated from a previous comment from @kraman-aws

2020-11-01 23:32 UTC, perifaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +{{% notice tip %}}
This is a tag from the Hugo template

2020-11-01 23:33 UTC, perifaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +You don't actually need to download the Cloudformation template to your Cloud9 instance. Indeed, it is possible to run Cloudformation templates that are already stored on S3. For that matter you coul
Good point, I'll comment it for now.

2020-11-01 23:36 UTC, perifaws commented on content/04-serverless/02-serverless-iam/_index.md
> +- Define an new [IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html) that we will apply on our cluster during the next step. This policy enables our instances to regist
Agreed, much clearer

2020-11-01 23:38 UTC, perifaws commented on content/04-serverless/04-slurm-lambda.md
> +Serverless functions, such as AWS Lambda, allow you to run code without provisioning or managing servers. It can be particularly useful to automate tasks or an infrastructure. In the present case we
HTTPS, changed on other docs

2020-11-01 23:40 UTC, perifaws commented
Thanks @mhuguesaws, PR updated based on comments.

2020-11-01 23:53 UTC, kraman-aws commented on content/04-serverless/_index.md
> +A [serverless](https://aws.amazon.com/serverless/) architecture enables you to build and run applications and services without having to manage an infrastructure. Your application still runs on serve
remove to

2020-11-01 23:57 UTC, kraman-aws commented on content/04-serverless/_index.md
> +A [serverless](https://aws.amazon.com/serverless/) architecture enables you to build and run applications and services without having to manage an infrastructure. Your application still runs on serve
Instead of "developing, operate at scale and on a reliable infrastructure"  -> "developing and operating on a reliable infrastructure at scale" ?

2020-11-01 23:57 UTC, kraman-aws commented on content/04-serverless/_index.md
> +In this lab you will be lead to build an HTTPS front-end to the Slurm scheduler. This front-end will be composed of an HTTPS API and a serverless function that will translate the HTTPS requests to Sl
led

2020-11-02 00:02 UTC, kraman-aws commented on content/04-serverless/02-serverless-iam/_index.md
> +- Define an new new [IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html) that enables the cluster instances to access SSM and access the S3 bucket.
"Define a new" , repeat new, change an to a

2020-11-02 00:04 UTC, kraman-aws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now you will create our policy. Let's start by downloading it. This step is not required but allows us to look at what new rights are being granted to our cluster.
your

2020-11-02 00:08 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +Serverless functions, such as AWS Lambda, allow you to run code without provisioning or managing servers. It can be particularly useful to automate tasks or an infrastructure. In the present case you
use your Lambda..

2020-11-02 00:08 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +Serverless functions, such as AWS Lambda, allow you to run code without provisioning or managing servers. It can be particularly useful to automate tasks or an infrastructure. In the present case you
on your cluster

2020-11-02 00:09 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +Serverless functions, such as AWS Lambda, allow you to run code without provisioning or managing servers. It can be particularly useful to automate tasks or an infrastructure. In the present case you
for your cluster

2020-11-02 00:10 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +In this section you will create our first serverless function, in the next section you will add the code of our function, then you will create an IAM Role and attach it to our function to allow it to
all "our" to be changed to "your"

2020-11-02 00:10 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +3. Leave all default settings except for the field **Function name** were you can enter **SlurmFrontEnd** and the field **Runtime**, choose **Python 3.8**.
where you can enter

2020-11-02 00:12 UTC, kraman-aws commented on content/04-serverless/04-slurm-lambda.md
> +You will be presented with an overview of your function and its different settings. In this panel. You can use it to configure which services or API call can trigger your function, layers to embed 3r
In this panel, you will be presented with an overview of your function and its different settings.

2020-11-02 00:13 UTC, kraman-aws commented on content/04-serverless/05-slurm-lambda-code.md
> +Now that you have created the Lambda function, you will add code to transform the HTTP requests to our cluster head - node through the channel offered by AWS Systems Manager(SSM). Let's add the code
to your cluster head node

2020-11-02 00:15 UTC, kraman-aws commented on content/04-serverless/06-slurm-lambda-config/_index.md
> +Now that you have added the code of our function you will add an environment variable then change the timeout of the function which is the maximum time this function is allowed to run.
add an environment variable to access your S3 bucket created earlier and also change the timeout of Lambda function..

2020-11-02 00:16 UTC, kraman-aws commented on content/04-serverless/06-slurm-lambda-config/06-config1.md
> +3. In the **Key** text box, enter the text `MY_S3_BUCKET`, in the **Value** field add the name of the S3 bucket that as created during [the very first step](/04-serverless/02-serverless-iam/02-iam-po
that was

2020-11-02 00:19 UTC, kraman-aws commented on content/04-serverless/06-slurm-lambda-config/06-config2.md
> +Now you will focus on IAM to modify the role for your lambda function in order to add the access rights required it needs to operate.
that it needs to operate or "in order to add the additional access rights required for it to operate"

2020-11-02 00:24 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/_index.md
> +The IAM changes you are conducting here with the AWS Console can also be using Cloudformation like in [*section b*](/04-serverless/02-iam-policy-serverless.html) or with the [AWS CLI](https://docs.aw
can also be done using AWS Cloudformation..

2020-11-02 00:29 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/07-final2.md
> +2. List your Amazon S3 buckets and pick the one you just created:
one you created in Section b. (provide link)?

2020-11-02 00:30 UTC, kraman-aws commented on content/04-serverless/07-slurm-lambda-final/07-final3.md
> +2. **Click on** the refresh button with **two arrows** (1 in the image) to refresh the policies list. Search for the name of the policy you just created (2 in the image), then select it and click **A
remove "a"

2020-11-02 00:32 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/_index.md
> +In this section, you will attach the AWS Lambda function created in the previous section with a [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) created using Amazon API Gate
your API... your lambda function

2020-11-02 00:33 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-api-gateway1.md
> +Now you will create our API Gateway and REST Resource:
your API

2020-11-02 00:34 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-api-gateway1.md
> +4. Now that you have an API you need to define a resource (similar to an object in [OOP](https://en.wikipedia.org/wiki/Object-oriented_programming)). Click on the button **Action**. Then select **Cre
Actions

2020-11-02 00:35 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-api-gateway1.md
> +You have defined our API Gateway and REST API. You will now link it to the Lambda function created earlier.
your API Gateway..

2020-11-02 00:35 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-api-gateway2.md
> +You will first define to which [HTTP methods](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods) our REST API will respond. You can bind different methods to different Lambda
your REST API..

2020-11-02 00:36 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-api-gateway2.md
> +1. In the Resource list, choose **/slurm** if not already selected. Click on the **Actions** dropdown menu then select u**Create Method**.
Remove "u" (typo)

2020-11-02 00:37 UTC, kraman-aws commented on content/04-serverless/08-api-gateway/08-api-gateway2.md
> +1. In the Resource list, choose **/slurm** if not already selected. Click on the **Actions** dropdown menu then select u**Create Method**.
The number formatting is messed up, amplify again i think

2020-11-02 00:42 UTC, kraman-aws commented on content/04-serverless/09-api-interact/_index.md
> +In the previous sections, you created a serverless function then binded a API Gateway to this function and trigger it using HTTPS calls. This function translates the arguments provided to the API Gat
then (bound?) an API Gateway to this function and triggered it using HTTPS calls.

2020-11-02 00:43 UTC, kraman-aws commented on content/04-serverless/09-api-interact/_index.md
> +In the previous sections, you created a serverless function then binded a API Gateway to this function and trigger it using HTTPS calls. This function translates the arguments provided to the API Gat
connects...executes

2020-11-02 00:44 UTC, kraman-aws commented on content/04-serverless/09-api-interact/_index.md
> +In the previous sections, you created a serverless function then binded a API Gateway to this function and trigger it using HTTPS calls. This function translates the arguments provided to the API Gat
you will use your new HTTPS API that you created and interact ..

2020-11-02 00:44 UTC, kraman-aws commented on content/04-serverless/09-api-interact/09-api-interact1.md
> +The list of parameters below are the ones that our Serverless function will be interpreting. The API will just forward the HTTPS calls content as an JSON object to our function.
a JSON

2020-11-02 00:45 UTC, kraman-aws commented on content/04-serverless/09-api-interact/09-api-interact1.md
> +| `jobscript_location` | Location of a job script to execute, it must be stored on Amazon S3 in our case. It required only when `function=submit_job`.
It is required..

2020-11-02 00:46 UTC, kraman-aws commented on content/04-serverless/09-api-interact/09-api-interact1.md
> +- **Head-node instance ID**: you will describe the instances using the command below. In the second column you will see a list of IDs, please pick the one corresponding to your head node.
should we provide a screen shot here?

2020-11-02 00:47 UTC, kraman-aws commented on content/04-serverless/09-api-interact/09-api-interact2.md
> +To interact wit your API you will be using [cURL](https://en.wikipedia.org/wiki/CURL), it is a tool commonly used to interact with HTTP(s) servers. cURL is already installed on your Cloud9 instance.
with (typo)

2020-11-02 00:54 UTC, kraman-aws requested changes
I have added additional comments. Please review

2020-11-02 01:10 UTC, perifaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now you will create our policy. Let's start by downloading it. This step is not required but allows us to look at what new rights are being granted to our cluster.
Fixed across all docs

2020-11-02 01:16 UTC, mhuguesaws commented on content/03-hpc-aws-parallelcluster-workshop/08-run-1stjob.md
> +![sinfo output](/images/hpc-aws-parallelcluster-workshop/helloworld-output.png)
That's hello world output

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/01-architecture.md
> +- [AWS Identity and Access Management (IAM)](https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html) provide tools to view and control your infrastructure. In the context of this lab, SSM
IAM def: 

[AWS Identity and Access Management (IAM)](https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html) provides a secure access management of AWS services and resources. You can also manage AWS users and groups, and use permissions to allow and deny their access to AWS resources.

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now you will create our policy. Let's start by downloading it. This step is not required but allows us to look at what new rights are being granted to our cluster.
still stands

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +Now you will create our policy. Let's start by downloading it. This step is not required but allows us to look at what new rights are being granted to our cluster.
not right, replace by permissions

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +The command above creates a Cloudformation stack as based on the template `serverless-template.yaml`. The policy name is specified in the template file. The `--stack-name` argument takes a unique nam
Cloud**F**ormation stack...

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/02-serverless-iam/02-iam-policy2.md
> +In the next section, you will change your AWS ParallelCluster configuration to add the `pclusterSSM` IAM policy and will apply the modified configuration to your cluster.
you will change your AWS ParallelCluster configuration file to add...

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/02-serverless-iam/_index.md
> +[Identity and Access Management](https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html) (IAM) controls who or what can conduct actions on resources. For example, an instance can be allow
To be consistent 

In the present case, you will enable the **instances**

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/02-serverless-iam/_index.md
> +- Define an new new [IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html) that enables the cluster instances to access SSM and access the S3 bucket.
to access SSM endpoints and the S3 bucket

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/03-configure-pc-serverless.md
> +{{% notice info %}}AWS ParallelCluster is an open source cluster management tool to deploy and manage HPC clusters with AWS. If you have not created a cluster, complete the [**Create an HPC Cluster**
still stands

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/03-configure-pc-serverless.md
> +Now that you have deployed a policy to enable our instances to register with AWS Systems Manager (SSM), you need to attach this policy to our instances. Let's start by reusing the the cluster you cre
have deployed a custom IAM policy

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/03-configure-pc-serverless.md
> +Now that you have deployed a policy to enable our instances to register with AWS Systems Manager (SSM), you need to attach this policy to our instances. Let's start by reusing the the cluster you cre
double the ->

**the** the AWS ParallelCluster **configuration** file created earlier

Spell full word

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/03-configure-pc-serverless.md
> +Now that you have deployed a policy to enable our instances to register with AWS Systems Manager (SSM), you need to attach this policy to our instances. Let's start by reusing the the cluster you cre
to update **your** existing cluster

2020-11-02 01:16 UTC, mhuguesaws commented on content/04-serverless/03-configure-pc-serverless.md
> +1. Begin by querying the Amazon Resource Name (ARN) of our newly created policy. This a unique name for each resources residing on your account that can be used as a reference. In our case, the ARN i
In this lab, the ARN is what you will use to reference the IAM policy in the cluster configuration file.

2020-11-02 14:55 UTC, merged

2020-11-02 15:01 UTC, mhuguesaws commented on content/04-serverless/03-configure-pc-serverless.md
> +{{% notice info %}}AWS ParallelCluster is an open-source cluster management service you can use to deploy and manage HPC clusters in AWS. If you have not created a cluster, complete the section [**Cr
ParallelCluster is not a service

2020-11-02 15:09 UTC, perifaws commented on content/04-serverless/03-configure-pc-serverless.md
> +{{% notice info %}}AWS ParallelCluster is an open-source cluster management service you can use to deploy and manage HPC clusters in AWS. If you have not created a cluster, complete the section [**Cr
It is officialy